version: '3.8'

services:
  postgres:
    container_name: facilita-juridico-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: facilita-juridico
      PGDATA: /data/postgres
 

  